---
title: "Non-coding Somatic Mutation From WXS"
author: "C.J. Liu"
date: "02/02/2017"
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    word_document:
      toc: yes
  word_document:
    toc: yes
---

# Challenges

## Non-coding Region
Ensembl release v86 Regulatory build. Regulatory regions cover 13% of whole human genome.

## WXS Data
For now, the pilot project. I use the most cases from TCGA - BRCA total 1098 cases.

Maybe I can collect other cancer types late.

...

## Call somatic mutation
GATK `HaplotypeCaller` algorithm call mutation with default parameters.

$somatic mutation = tumor mutation - normal mutation$

Filter criterion

||Tumor|Normal|
|---|---|---|
|MQ|>=20|>=20|
|DP|>=10|>=5|
|AD|>=3|>=3|

> Then Get all somatic mutation

**********************************

# Story clue

## WXS vs. WGS

### Total Number of WXS and WGS for BRCA (or For all TCGA cancer types)

### File size comparison

1. raw WGS vs. raw WXS
2. extracted regulatory WGS vs. WXS

### Somtatic mutation number with file size
regulatory somatic mutation number WGS vs. WXS

### Somatic mutation overlap
somatic mutation overlap between WGX and WXS.


## Novel recurrent somatic mutation

















