---
title: "PDE4DIP Methylation"
author: "C.J. Liu"
date: "1/11/2017"
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    word_document:
      toc: yes
  word_document:
    toc: yes
---

# PDE4DIP Methylation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load library}
suppressMessages(require(dplyr))
suppressMessages(require(tidyr))
suppressMessages(require(MASS))
```


```{r load data}
# PDE4DIP expression
ROOT='/home/cliu18/liucj/projects/1.Mutation_calling_in_non-condig_region_through_EXOME/8.expression'
PDE4DIP.expression <- read.table(file = file.path(ROOT, 'PDE4DIP.expression.txt'), header = T, sep = "\t" )

header <- as.character(unname(unlist(read.table(file = '/extraspace/TCGA/WXS_RAW/BRCA/Methylation/downloadList/header', sep = "\t"))))

#load Methylation data.
methPath <- '/extraspace/TCGA/WXS_RAW/BRCA/Methylation/downloadList/Meth450'
sampleNames <- dir(methPath)

#merge all tables
methData <- data.frame(REF=c("cg03866074","cg09366969","cg10010376","cg10505902","cg12594911"))
for(i in sampleNames){
  #print(file.path(methPath, i))
  samplePath <- file.path(methPath, i)
  tmp <- read.table(file = samplePath, sep = "\t")[c(1,2)]
  names(tmp) <- c("REF", i)
  methData <- left_join(methData,tmp, by="REF")
}

# rownames(methData) <- methData$REF
methData <- gather(methData, barcode, beta_value, -REF)

# gather(methData, Sample, Beta_value, -REF)
methData$barcode <- gsub('-','.',methData$barcode)
meth.expr <- left_join(methData, PDE4DIP.expression, by = 'barcode')

# lm data preparation
meth.expr.refSpread <- meth.expr %>% spread(REF, beta_value) %>% mutate(mutation = ifelse(type == "MT", 1, 0)) %>% dplyr::select(expression:mutation)  
meth.expr.refSpread.scaled <- as.data.frame(scale(meth.expr.refSpread))

# lm
meth.expr.refSpread.scaled.lm <- lm(expression ~ ., data = meth.expr.refSpread.scaled)
# Model selection
meth.expr.refSpread.scaled.lm.update <- stepAIC(meth.expr.refSpread.scaled.lm, ~., trace = F)
meth.expr.refSpread.scaled.lm.update.summary <- summary(meth.expr.refSpread.scaled.lm.update)

model.pvalue <- with(as.data.frame(as.list(meth.expr.refSpread.scaled.lm.update.summary$fstatistic)), pf(value, numdf, dendf, lower.tail = F))

# calculate partial correlation
PartialCorr <- coef(meth.expr.refSpread.scaled.lm.update.summary)[-1,'Estimate']
Pr_coefs <- coef(meth.expr.refSpread.scaled.lm.update.summary)[-1,'Pr(>|t|)']

nameEssence <- rownames(coef(meth.expr.refSpread.scaled.lm.update.summary))[-1]
names(Pr_coefs) <- sprintf("Pvalue_%s",nameEssence)
names(PartialCorr) <- sprintf("PartialCorr_%s",nameEssence)
adjRsq <- meth.expr.refSpread.scaled.lm.update.summary$adj.r.squared

meth.expr.refSpread.scaled.lm
opar <- par(mfrow = c(2,2), oma = c(0, 0, 1.1, 0))
plot(meth.expr.refSpread.scaled.lm, las = 1)      # Residuals, Fitted, ...
par(opar)
meth.expr.refSpread.scaled.lm.update
# then the spearman corr with no adjustments on other covariates
opar <- par(mfrow = c(2,2), oma = c(0, 0, 1.1, 0))
plot(meth.expr.refSpread.scaled.lm.update, las = 1)      # Residuals, Fitted, ...
par(opar)
```

