---
title: "PDE4DIP_Survival_Analysis"
author: "C.J. Liu"
date: "1/18/2017"
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    word_document:
      toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Survival Analysis

```{r load library}
suppressMessages(require(dplyr))
suppressMessages(require(tidyr))
suppressMessages(require(survival))
suppressMessages(require(survminer))
```
```{r load PDE4DIP expression}
ROOT='/home/cliu18/liucj/projects/1.Mutation_calling_in_non-condig_region_through_EXOME/8.expression'
PDE4DIP.gene.expression <- read.table(file = file.path(ROOT, 'PDE4DIP.expression.txt'), header = T, sep = "\t" )

PDE4DIP.gene.expression.noNM <- PDE4DIP.gene.expression %>% filter(type %in% c("MT","WT"))

PDE4DIP.gene.expression.noNM$barcode <- gsub('\\.','-',substr(as.character(PDE4DIP.gene.expression.noNM$barcode), 1,12))
```

```{r load clinical data}
ROOT = '/home/cliu18/liucj/projects/1.Mutation_calling_in_non-condig_region_through_EXOME/9.Survival'
clinical <- read.table(file = file.path(ROOT, 'BRCA_clinical_clean.PDE4DIP.txt'), header = T, sep = "\t")
```
```{r merge clinical and expression}
mutation.clinical.expression <- clinical %>% dplyr::select(barcode,time = os_days, status = os_status) %>% inner_join(PDE4DIP.gene.expression.noNM, by = 'barcode')

mutation.clinical.expression$status <- ifelse(mutation.clinical.expression$status == "Dead", 1, 0)

#mutation.clinical.expression$type <- ifelse(mutation.clinical.expression$type == "MT", 1, 0)
```


## PDE4DIP expression signal samples
```{r expression}
# Calculate the 
model.expression <- coxph(Surv(time, status) ~ expression, data=mutation.clinical.expression, na.action=na.exclude)
summary(model.expression)$coefficients[1,c("coef", "exp(coef)", "Pr(>|z|)" )]

# cut group as median expression
mutation.clinical.expression$group <- ifelse(as.vector(mutation.clinical.expression$expression) <= median(as.vector(mutation.clinical.expression$expression)), "Low","High")

model.expression <- survdiff(Surv(time, status) ~ group, data= mutation.clinical.expression, na.action=na.exclude)

e.Low <- mean(mutation.clinical.expression$group == "Low")
e.High <- mean(mutation.clinical.expression$group == "High")
e.FC <- log2((e.Low + 1)/(e.High + 1))

e.fit <- survfit(Surv(time, status) ~ group, data = mutation.clinical.expression, na.action = na.exclude)

ggsurvplot(e.fit, pval=T, ggtheme = theme_light(), xlab = "Survival in days", ylab = '', main = paste("Kaplan-Meier Curves PDE4DIP Expression",sep=""))
```


## Point mutation chr1:148661032A>T signal samples
```{r mutation}

model.mutation <- survdiff(Surv(time, status) ~ type, data = mutation.clinical.expression)

m.KMp <- 1 - pchisq(model.mutation$chisq, df = length(levels(factor(mutation.clinical.expression$type))) - 1)
m.MT <- mean(mutation.clinical.expression$type == "MT")
m.WT <- mean(mutation.clinical.expression$type == "WT")
m.FC <- log2((m.MT + 1)/(m.WT + 1))

m.fit <- survfit(Surv(time, status) ~ type, data = mutation.clinical.expression, na.action = na.exclude)

ggsurvplot(m.fit, pval=T, ggtheme = theme_light(), xlab = "Survival in days", ylab = '', main = paste("Kaplan-Meier Curves PDE4DIP Mutation",sep=""))

```

## PDE4DIP all sample expression
### All samples
```{r all samples}
###
#PDE4DIP expression all samples
###
dataPath = '/extraspace/TCGA/WXS_RAW/BRCA/RNA-seq'

PDE4DIP.all.expression <- read.table(file.path(dataPath, 'PDE4DIP.all.expr.txt'), header = T, sep = "\t" )

PDE4DIP.all.expression.gather <- gather(PDE4DIP.all.expression, barcode, expression, -ensid)

PDE4DIP.all.expression.gather$barcode <- gsub('\\.','-',substr(as.character(PDE4DIP.all.expression.gather$barcode), 1,12))

###
# all clinical data
###
clinical.all <- read.table(file = file.path(ROOT, 'BRCA_clinical_clean.txt'), header = T, sep = "\t")

all.clinical.expression <- clinical.all %>% dplyr::select(barcode,time = os_days, status = os_status) %>% inner_join(PDE4DIP.all.expression.gather, by = 'barcode')

###
# filter time or status is na
###
all.clinical.expression.filter <- all.clinical.expression %>% filter(!is.na(time) & !is.na(status) & as.numeric(time) >= 0)

all.clinical.expression.filter$status <- ifelse(all.clinical.expression.filter$status == "Dead", 1, 0)

###
# Calculate the 
###
model.expression.all <- coxph(Surv(time, status) ~ expression, data=all.clinical.expression.filter, na.action=na.exclude)

summary(model.expression.all)$coefficients[1,c("coef", "exp(coef)", "Pr(>|z|)" )]

###
# cut group as median expression
###
all.clinical.expression.filter$group <- ifelse(as.vector(all.clinical.expression.filter$expression) <= median(as.vector(all.clinical.expression.filter$expression)), "Low","High")

model.expression.all <- survdiff(Surv(time, status) ~ group, data= all.clinical.expression.filter, na.action=na.exclude)

e.Low <- mean(all.clinical.expression.filter$group == "Low")

e.High <- mean(all.clinical.expression.filter$group == "High")

e.FC <- log2((e.Low + 1)/(e.High + 1))

e.fit <- survfit(Surv(time, status) ~ group, data = all.clinical.expression.filter, na.action = na.exclude)

ggsurvplot(e.fit, pval=T, ggtheme = theme_light(), xlab = "Survival in days", ylab = '', main = paste("Kaplan-Meier Curves PDE4DIP Expression",sep=""))
```

### Top and bottom 1/4
```{r select 1/4}
all.clinical.expression.filter.top <- all.clinical.expression.filter %>% top_n(round(nrow(all.clinical.expression.filter) / 4, digits = 0), expression)

all.clinical.expression.filter.bottom <- all.clinical.expression.filter %>% top_n(-round(nrow(all.clinical.expression.filter) / 4, digits = 0), expression)

all.clinical.expression.filter.sub <- dplyr::union(all.clinical.expression.filter.top, all.clinical.expression.filter.bottom)


###
# Calculate the 
###
model.expression.all.sub <- coxph(Surv(time, status) ~ expression, data=all.clinical.expression.filter.sub, na.action=na.exclude)

summary(model.expression.all.sub)$coefficients[1,c("coef", "exp(coef)", "Pr(>|z|)" )]

###
# cut group as median expression
###
model.expression.all.sub <- survdiff(Surv(time, status) ~ group, data= all.clinical.expression.filter.sub, na.action=na.exclude)

e.Low <- mean(all.clinical.expression.filter.sub$group == "Low")

e.High <- mean(all.clinical.expression.filter.sub$group == "High")

e.FC <- log2((e.Low + 1)/(e.High + 1))

e.fit <- survfit(Surv(time, status) ~ group, data = all.clinical.expression.filter.sub, na.action = na.exclude)

ggsurvplot(e.fit, pval=T, ggtheme = theme_light(), xlab = "Survival in days", ylab = '', main = paste("Kaplan-Meier Curves PDE4DIP Expression",sep=""))

```





































