---
title: "TCGA RBCA data summary"
author: "C.J. Liu"
date: "11/22/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
> Data downloaded from GDC TCGA-BRCA project WXS

```{r load library}
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(humanFormat))
```

```{r load data}
manifest <- as_data_frame(read.table('BRCA_gdc_manifest.2016-11-16T20-32-04.345034.tsv', header = T, sep = "\t"))
submitter <- as_data_frame(read.table('BRCA_gdc_manifest.2016-11-16T20-32-04.345034.tsv.map2submitterID', header = T, sep = "\t"))
manifest <- rename(manifest,  file_id = id)

# Merge data frame
brca <- inner_join(manifest, submitter, by = "file_id")
```

## Case pairs distribution
```{r}
brca.pairs <- brca %>% group_by(cases_0_case_id) %>% summarise(count = n()) %>% arrange(-count)

ggplot(brca.pairs, aes(x = as.factor(count))) + geom_bar(fill = "steelblue") + geom_text(stat = 'count', aes(label = ..count..), vjust = -0.3, size = 3) + theme_minimal() + xlab("NO. cases")
```


```{r}
# Remove no cases pairs
brca.pairs.nopairs <- filter(brca.pairs, count == 1)

brca.rmNoPairs <- brca %>% filter(! cases_0_case_id  %in%  brca.pairs.nopairs$cases_0_case_id)
```

## Sample type distribution after removing no pairs
```{r}
ggplot(brca.rmNoPairs, aes(x = cases_0_samples_0_sample_type)) + geom_bar(fill = 'steelblue') + geom_text(stat = 'count', aes(label = ..count..), vjust = -0.3, size = 3) + theme_minimal() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("Sample Type") + scale_x_discrete(limits = c('Primary Tumor','Metastatic','Blood Derived Normal','Solid Tissue Normal'))
```

## Data size
```{r}
totalDataSize <- brca.rmNoPairs %>% group_by(cases_0_samples_0_sample_type) %>% summarise(number=sum(size)) %>% mutate(storage = formatBytes(number)) %>% arrange(- number)

ggplot(totalDataSize, aes(x="", y = number, fill = paste(cases_0_samples_0_sample_type, paste("(",storage, ")", sep = "")))) + geom_bar(width = 1, stat = 'identity') + theme_minimal() + coord_polar("y", start = 0) + theme(axis.text.x=element_blank()) + guides(fill = guide_legend(title = "Sample Type"))

```

# Write Normal and Tumor result to TSV files.
```{r}
brca.normal <- filter(brca.rmNoPairs, grepl("Normal",cases_0_samples_0_sample_type))
write.table(brca.normal, file = "brca.normal.manifest.tsv", quote = FALSE, sep = "\t", row.names = FALSE)
brca.tumor <- filter(brca.rmNoPairs, ! grepl("Normal",cases_0_samples_0_sample_type))
write.table(brca.tumor, file = "brca.tumor.manifest.tsv", quote = FALSE, sep = "\t", row.names = FALSE)
```



