---
title: "TCGA LUAD data summary"
author: "C.J. Liu"
date: "1/6/2017"
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    word_document:
      toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```
```{r load library}
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(humanFormat))
```
#TCGA LUAD data summary
```{r load data}
root='/extraspace/TCGA/WXS_RAW/LUAD/downloadDataList'
manifest <- as_data_frame(read.table(file.path(root,'gdc_manifest.2017-01-06T22-09-50.454874.tsv'), header = T, sep = "\t"))
submitter <- as_data_frame(read.table(file.path(root,'gdc_manifest.2017-01-06T22-09-50.454874.tsv.map2submitterID'), header = T, sep = "\t"))
manifest <- rename(manifest,  file_id = id)

# Merge data frame
luad <- inner_join(manifest, submitter, by = "file_id")
```

## Case pairs distribution
```{r}
luad.pairs <- luad %>% group_by(cases_0_case_id) %>% summarise(count = n()) %>% arrange(-count)

ggplot(luad.pairs, aes(x = as.factor(count))) + geom_bar(fill = "steelblue") + geom_text(stat = 'count', aes(label = ..count..), vjust = -0.3, size = 3) + theme_minimal() + xlab("NO. cases")
```


```{r}
# Remove no cases pairs
luad.pairs.nopairs <- filter(luad.pairs, count == 1)

luad.rmNoPairs <- luad %>% filter(! cases_0_case_id  %in%  luad.pairs.nopairs$cases_0_case_id)
```

## Sample type distribution after removing no pairs
```{r}
ggplot(luad.rmNoPairs, aes(x = cases_0_samples_0_sample_type)) + geom_bar(fill = 'steelblue') + geom_text(stat = 'count', aes(label = ..count..), vjust = -0.3, size = 3) + theme_minimal() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab("Sample Type") + scale_x_discrete(limits = c('Primary Tumor','Recurrent Tumor','Blood Derived Normal','Solid Tissue Normal','FFPE Scrolls'))
```

## Data size
```{r}
totalDataSize <- luad.rmNoPairs %>% group_by(cases_0_samples_0_sample_type) %>% summarise(number=sum(size)) %>% mutate(storage = formatBytes(number)) %>% arrange(- number)

ggplot(totalDataSize, aes(x="", y = number, fill = paste(cases_0_samples_0_sample_type, paste("(",storage, ")", sep = "")))) + geom_bar(width = 1, stat = 'identity') + theme_minimal() + coord_polar("y", start = 0) + theme(axis.text.x=element_blank()) + guides(fill = guide_legend(title = "Sample Type"))

```

## Write Normal and Tumor result to TSV files.
```{r}
luad.normal <- filter(luad.rmNoPairs, grepl("Normal",cases_0_samples_0_sample_type))
write.table(luad.normal, file = file.path(root,"luad.normal.manifest.tsv"), quote = FALSE, sep = "\t", row.names = FALSE)
luad.tumor <- filter(luad.rmNoPairs, ! grepl("Normal",cases_0_samples_0_sample_type))
write.table(luad.tumor, file = file.path(root,"luad.tumor.manifest.tsv"), quote = FALSE, sep = "\t", row.names = FALSE)
```