---
title: "RegressionAnalysis"
author: "C.J. Liu"
date: "1/24/2017"
output:
  html_document:
    depth: 3
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    word_document:
      toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Simple regression

```{r}
require(ggplot2)
require(nutshell)
require(GGally)
require(ggcorrplot)
data("team.batting.00to08")
summary(team.batting.00to08)
cor(team.batting.00to08[,3:10])
ggcorr(team.batting.00to08[,3:10], palette = "Set3", label = T)
ggpairs(team.batting.00to08[,3:10])

p.mat <- cor_pmat(team.batting.00to08[,3:10])
p.mat
ggcorrplot(round(cor(team.batting.00to08[,3:10]),1))
ggcorrplot(round(cor(team.batting.00to08[,3:10]),1), hc.order = T, outline.color = 'white')
ggcorrplot(round(cor(team.batting.00to08[,3:10]),1), hc.order = T, type = 'lower', p.mat = p.mat)
ggcorrplot(round(cor(team.batting.00to08[,3:10]),1), hc.order = T, outline.color = 'white', type='lower', ggtheme = ggplot2::theme_bw, lab = T)


runs.lm <- lm(runs~singles+doubles+triples+homeruns+walks+hitbypitch+sacrificeflies+stolenbases+caughtstealing,data=team.batting.00to08)

summary(runs.lm)

# rm unsignificant variable by hand
runs.lm_a <- lm(runs~singles+doubles+triples+homeruns+walks+hitbypitch+sacrificeflies,data=team.batting.00to08)

# rm unsignificant variable automatically
runs.lm_b<-step(runs.lm)


```


# Step regression
```{r}
library(MASS)

runs.lm <- lm(runs~singles+doubles+triples+homeruns+walks+hitbypitch+sacrificeflies+stolenbases+caughtstealing,data=team.batting.00to08)

lm_back<-stepAIC(runs.lm,direction = "backward")

summary(lm_back)

```

# Ridge regression
```{r}
cement <- data.frame(X1 = c(7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10), X2 = c(26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68), X3 = c(6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8), X4 = c(60, 52, 20, 47, 33, 22, 6, 44, 22, 26,34, 12, 12), Y = c(78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1,115.9, 83.8, 113.3, 109.4))
cement
lm.sol <- lm(Y ~ ., data = cement)
summary(lm.sol)
stepAIC(lm.sol)

library(car)
vif(lm.sol)
ggplot(data = cement, aes(x=X2, y = X4)) + geom_point() + geom_smooth(method = lm)

ridge.sol <- lm.ridge(Y ~ ., lambda = seq(0, 150, length = 151), data = cement, model = TRUE)
summary(ridge.sol)
ridge.sol$lambda[which.min(ridge.sol$GCV)]
ridge.sol$coef[which.min(ridge.sol$GCV)]
par(mfrow = c(1, 2))
matplot(ridge.sol$lambda, t(ridge.sol$coef), xlab = expression(lamdba), ylab = "Cofficients", type = "l", lty = 1:20)
abline(v = ridge.sol$lambda[which.min(ridge.sol$GCV)])

plot(ridge.sol$lambda, ridge.sol$GCV, type = "l", xlab = expression(lambda),ylab = expression(beta))
abline(v = ridge.sol$lambda[which.min(ridge.sol$GCV)])

par(mfrow = c(1, 1))

library(ridge)
mod <- linearRidge(Y ~ ., data = cement)
summary(mod)

library(lars)
x = as.matrix(cement[, 1:4])
y = as.matrix(cement[, 5])
(laa = lars(x, y, type = "lar"))
plot(laa)
summary(laa)
```





